platform:
  - x64
environment:
  global:
    APPVEYOR_OS_NAME: windows
    RUBY_VERSION: "22-x64"
    GOPATH: c:\gopath
    BINTRAY_USER:
      secure: HvXDg/3xn3Du2GPXPyf1tQ==
    BINTRAY_APIKEY:
      secure: pKFoGMJ1yEvd9hI9yF8a7D5fp5xGt53GdSrV3/g2CVbWiUfNoAXyYzHC1R4jSUqQ
  matrix:
    #- MSYS2_ARCH: x86_64
    #  MSYS2_BITS: 64
    #  MSYSTEM: MSYS2
    #  METHOD: ci
    #- MSYS2_ARCH: i686
    #  MSYS2_BITS: 32
    #  MSYSTEM: MINGW32
    #  METHOD: cross
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      METHOD: cross
      MSYS2_BASEVER: 20150916
install:
  - '%APPVEYOR_BUILD_FOLDER%\ci\install-win.bat'
build_script:
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/twstrike/coyim && make build-gui"'
artifacts:
  - path: '%GOPATH%\src\github.com\twstrike\coyim\bin\coyim.exe'
before_deploy:
  - '%MSYS_PATH%\usr\bin\bash -lc "pacman --noconfirm --needed -Sy sed" > $nul'
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/twstrike/coyim && ci/release-win"'
deploy_script:
  - '%MSYS_PATH%\usr\bin\bash -lc "gem install dpl && cd /c/gopath/src/github.com/twstrike/coyim && dpl --provider=bintray --file=ci/bintray.json --user=%BINTRAY_USER% --key=%BINTRAY_APIKEY%"'
