language: go

go:
  - tip
  - 1.5
  - 1.4.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libgtk-3-dev
  # - sudo apt-get install -qq -y gtk+3.0 libgtk-3-dev

install:
  #- go get -tags gtk_3_6 -v github.com/twstrike/gotk3
  - make deps

script: make ci

sudo: required
dist: trusty
