language: go

go:
  - tip
  - 1.5
  - 1.4.2

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

install: make deps

script:
  - make ci
  - $HOME/gopath/bin/goveralls -service=travis-ci || true
